version: '3.8'

services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: 84Eyk137PHhJ
      MYSQL_DATABASE: mqtt
      MYSQL_USER: dev
      MYSQL_PASSWORD: dev
    ports:
      - "3306:3306"

  keycloak:
    image: keycloak/keycloak:latest
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      KEYCLOAK_IMPORT: /tmp/keycloak-realm.json
    ports:
      - "8080:8080"
    volumes:
      - ./keycloak-realm.json:/tmp/keycloak-realm.json

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8081"

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
